import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideNav from './ui/sidenav'
import { getServerSession } from 'next-auth'
import SessionProvider from "./components/sessionProvider"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession();
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <SessionProvider session={session}>
            <div className="w-full flex-none md:w-64">
              <SideNav />
            </div>          
            <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
          </SessionProvider>
        </div>  
      </body>
    </html>
  )
}
