name: Run All Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: npm  install
        - name: Install Playwright
          run: npx playwright install --with-deps
        - name: Run Jest
          run: npm run test
        - name: Run Playwright tests
          run: npm run test:e2e